# Common
minecraft_version=1.20.1
jei_version=15.20.0.129
rei_version=12.1.785
jade_api_id=4712550
jade_id=4711195

# Forge
forge_version=47.4.+
mapping_channel=official
mapping_version=1.20.1

# Mod options
mod_name=Wooden Utilities
mod_author=ModernGamingWorld
mod_id=woodenutilities
mod_version=1.0.0
maven_group=com.moderngamingworld
mod_homepage=https://www.curseforge.com/minecraft/mc-mods/wooden-utilities
mod_source=https://github.com/ModernGamingWorlds-Mods/Wooden-Utilities
mod_issues=https://github.com/ModernGamingWorlds-Mods/Wooden-Utilities/issues
mod_description=Wooden Utilities is a Mod based around adding many Wood related items to the game.
mod_license=MIT

# Gradle
org.gradle.daemon=false
org.gradle.jvmargs=-Xmx3G

# CurseForgeGradle
curse_project=409871

# Modrinth
modrinth_project=tDuD4nCF
