    modLoader="javafml"
    loaderVersion="${loader_version_range}"
    license="${mod_license}"
    issueTrackerURL="https://github.com/ModernGamingWorlds-Mods/Wooden-Utilities/issues"

    [[mods]]
       modId="woodenutilities"
       version="${mod_version}"
       displayName="${mod_name}"
       displayURL="https://legacy.curseforge.com/minecraft/mc-mods/wooden-utilities"
       logoFile= "../EXAMPLE_ITEM.png"
       authors="${mod_authors}"
       description='''${mod_description}'''

    [[dependencies.${mod_id}]]
       modId="neoforge"
       type="required"
       versionRange="${neo_version_range}"
       ordering="NONE"
       side="BOTH"

    [[dependencies.${mod_id}]]
       modId="minecraft"
       type="required"
       versionRange="${minecraft_version_range}"
       ordering="NONE"
       side="BOTH"