modLoader="javafml"
loaderVersion="[37,)"
license="MIT"
issueTrackerURL="https://github.com/ModernGamingWorlds-Mods/Wooden-Utilities/issues"

[[mods]]
modId="woodenutilities"
version="${file.jarVersion}"
displayName="Wooden Utilities"
displayURL="https://www.curseforge.com/minecraft/mc-mods/wooden-utilities"
credits="NovaMachina, LazyMinded, and many others"
authors="ModernGamingWorld, NovaMachina, LazyMinded"
description='''An all-new Minecraft Mod that adds more Wood-Related items to your daily Minecraft Experience.'''

[[dependencies.woodenutilities]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.woodenutilities]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1, 1.18)"
    ordering="NONE"
    side="BOTH"

[[dependencies.woodenutilities]]
   modId="libx"
   mandatory=true
   versionRange="[1.17.1-2.0.19,)"
   ordering="NONE"
   side="BOTH"
