modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/ModernGamingWorlds-Mods/Wooden-Utilities/issues"
[[mods]]
modId="woodenutilities"
version="${version}"
displayName="Wooden Utilities"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
#logoFile="examplemod.png" #optional
credits="Thanks people"
authors="ModernGamingWorld, NovaMachina, LazyMinded"
description='''
Wooden Utilities, an all-new Minecraft Mod that adds more Wood-Related items to your daily Minecraft Experience.
'''
[[dependencies.woodenutilities]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version}"
    ordering="NONE"
    side="BOTH"
[[dependencies.woodenutilities]]
    modId="minecraft"
    mandatory=true
    versionRange="${mc_version}"
    ordering="NONE"
    side="BOTH"
