modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/ModernGamingWorlds-Mods/Wooden-Utilities/issues"

[[mods]]
modId="woodenutilities"
version="${version}"
displayName="Wooden Utilities"
displayURL="https://www.curseforge.com/minecraft/mc-mods/wooden-utilities"
credits="NovaMachina, LazyMinded, and many others"
authors="ModernGamingWorld, NovaMachina, LazyMinded"
description='''An all-new Minecraft Mod that adds more Wood-Related items to your daily Minecraft Experience.'''

[[dependencies.woodenutilities]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version}"
    ordering="NONE"
    side="BOTH"
[[dependencies.woodenutilities]]
    modId="minecraft"
    mandatory=true
    versionRange="${mc_version}"
    ordering="NONE"
    side="BOTH"
